# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default_twitter: &default_twitter
  twitter_api_key: 'SZJE9SQflCaKHoFMSIN3VaO8V'
  twitter_api_secret: '38aC5v6Ugkp9osPI9r3rFnUOTslAdKah4ZizdvA49j0hvAMXqv'

development:
  secret_key_base: e8ec9a4135e3e23804ac1e99f86b5f1156cde464a61ea417fdb10060244b610cda608a57278cfc4f3337beed7689f4e39e3b4e9bd5ff1a80e47f756154c06e7a
  <<: *default_twitter

test:
  secret_key_base: c92bd5e46d6b9f097fad194087c3ecf16948441cd411ad8c039e38f142e54900cef0ea6e080c04920d955d74dc9012690d542a79ddfadc930400876e77702c9c
  <<: *default_twitter

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <% ENV["TWITTER_CONSUMER_SECRET"] %>
